name: build

on:
  push:
    branches: main

jobs:

  build_and_push:

    runs-on: ubuntu-latest
    container: ubuntu_with_extras
    
    steps:
      - uses: actions/checkout@v2

      # scan the python code with bandit sast
      - name: run bandit sast
        run: docker run --rm -i opensorcery/bandit -r .
      
      # check the dockerfile with hadolint for security/misconfiguration issues
      - name: check the dockerfile with hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile

      # build the image
      - name: build image
        run: docker build -t local_app .

      # scan image with trivy
      - name: run trivy container vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: local_app
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      