name: build

on:
  push:
    branches: main

jobs:

  build_and_push:

    runs-on: ubuntu-latest
    container: ubuntu_with_extras
    env:
      REGISTRY: docker.pkg.github.com
      IMAGE_ID: docker.pkg.github.com/${{ github.repository }}/application:latest
    steps:
      #- uses: actions/checkout@v2

      # scan the python code with bandit sast
      #- name: run bandit sast
      #  uses: tj-actions/bandit@v5
      #  with:
      #    targets: .
      #    options: "-r"
      
      # check the dockerfile with hadolint for security/misconfiguration issues
      - name: check the dockerfile with hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile

      # build the image
      - name: build image
        run: docker build -t ${{ env.IMAGE_ID }} .

      # scan image with trivy
      - name: run trivy container vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_ID }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      